In [ ]:
import torch
import numpy as np

# 1. Tạo tensor từ list
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(f"Tensor từ list:\n {x_data}\n")

# 2. Tạo tensor từ NumPy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f"Tensor từ NumPy array:\n {x_np}\n")

# 3. Tạo tensor với các giá trị ngẫu nhiên hoặc hằng số
x_ones = torch.ones_like(x_data) # tạo tensor toàn số 1, cùng shape với x_data
print(f"Ones Tensor:\n {x_ones}\n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # tạo tensor ngẫu nhiên [0, 1)
print(f"Random Tensor:\n {x_rand}\n")

# 4. Kiểm tra thuộc tính
print(f"Shape của tensor: {x_rand.shape}")
print(f"Datatype của tensor: {x_rand.dtype}")
print(f"Device lưu trữ tensor: {x_rand.device}")

Tensor từ list:
 tensor([[1, 2],
        [3, 4]])

Tensor từ NumPy array:
 tensor([[1, 2],
        [3, 4]])

Ones Tensor:
 tensor([[1, 1],
        [1, 1]])

Random Tensor:
 tensor([[0.4282, 0.4885],
        [0.7854, 0.5143]])

Shape của tensor: torch.Size([2, 2])
Datatype của tensor: torch.float32
Device lưu trữ tensor: cpu


In [ ]:
# 1. Cộng x_data với chính nó
sum_tensor = x_data + x_data
print(f"Cộng x_data với chính nó:\n {sum_tensor}\n")

# 2. Nhân x_data với 5 (Scalar multiplication)
mul_scalar = x_data * 5
print(f"Nhân x_data với 5:\n {mul_scalar}\n")

# 3. Nhân ma trận x_data với x_data.T (Matrix Multiplication)
# x_data.T là ma trận chuyển vị
matrix_mul = x_data @ x_data.T
# Hoặc dùng: matrix_mul = torch.matmul(x_data, x_data.T)
print(f"Nhân ma trận x_data với chuyển vị của nó:\n {matrix_mul}")

Cộng x_data với chính nó:
 tensor([[2, 4],
        [6, 8]])

Nhân x_data với 5:
 tensor([[ 5, 10],
        [15, 20]])

Nhân ma trận x_data với chuyển vị của nó:
 tensor([[ 5, 11],
        [11, 25]])


In [ ]:
# Giả sử x_data là [[1, 2], [3, 4]]

# 1. Lấy ra hàng đầu tiên (index 0)
first_row = x_data[0]
print(f"Hàng đầu tiên: {first_row}")

# 2. Lấy ra cột thứ hai (tất cả các hàng, index cột là 1)
second_column = x_data[:, 1]
print(f"Cột thứ hai: {second_column}")

# 3. Lấy ra giá trị ở hàng thứ hai, cột thứ hai (index 1, 1)
last_value = x_data[1, 1]
print(f"Giá trị tại hàng 2, cột 2: {last_value}")

Hàng đầu tiên: tensor([1, 2])
Cột thứ hai: tensor([2, 4])
Giá trị tại hàng 2, cột 2: 4


In [ ]:
# Tạo tensor có shape (4, 4)
tensor_4x4 = torch.rand(4, 4)
print(f"Shape ban đầu: {tensor_4x4.shape}")

# Biến đổi thành shape (16, 1)
# Cách 1: Dùng view (yêu cầu bộ nhớ liên tục)
tensor_16x1 = tensor_4x4.view(16, 1)

# Cách 2: Dùng reshape (linh hoạt hơn)
# tensor_16x1 = tensor_4x4.reshape(16, 1)

print(f"Shape sau khi biến đổi: {tensor_16x1.shape}")
print(f"Dữ liệu sau khi reshape:\n {tensor_16x1}")

Shape ban đầu: torch.Size([4, 4])
Shape sau khi biến đổi: torch.Size([16, 1])
Dữ liệu sau khi reshape:
 tensor([[0.3517],
        [0.7447],
        [0.7551],
        [0.6372],
        [0.9853],
        [0.6584],
        [0.4792],
        [0.6810],
        [0.5404],
        [0.9117],
        [0.9112],
        [0.2880],
        [0.5468],
        [0.2508],
        [0.8145],
        [0.0492]])


In [ ]:
import torch

# Tạo một tensor và yêu cầu tính đạo hàm cho nó (requires_grad=True)
x = torch.ones(1, requires_grad=True)
print(f"x: {x}")

# Thực hiện phép toán: y = x + 2
y = x + 2
print(f"y: {y}")
print(f"grad_fn của y: {y.grad_fn}") # Cho biết y được tạo từ phép cộng (Add)

# Thực hiện thêm phép toán: z = y * y * 3 => z = 3 * (x + 2)^2
z = y * y * 3
print(f"z: {z}")

# Tính đạo hàm của z theo x
z.backward()

# Kết quả đạo hàm dz/dx tại x=1
print(f"Đạo hàm của z theo x: {x.grad}")

x: tensor([1.], requires_grad=True)
y: tensor([3.], grad_fn=<AddBackward0>)
grad_fn của y: <AddBackward0 object at 0x78fe80072e00>
z: tensor([27.], grad_fn=<MulBackward0>)
Đạo hàm của z theo x: tensor([18.])


In [ ]:
import torch
from torch import nn

# Khởi tạo lớp Linear: 5 đầu vào -> 2 đầu ra
linear_layer = nn.Linear(in_features=5, out_features=2)

# Tạo tensor đầu vào mẫu: 3 mẫu dữ liệu, mỗi mẫu có 5 đặc trưng
input_tensor = torch.randn(3, 5)

# Truyền qua lớp linear
output = linear_layer(input_tensor)

print(f"Input shape: {input_tensor.shape}") # torch.Size([3, 5])
print(f"Output shape: {output.shape}")      # torch.Size([3, 2])
print(f"Output:\n {output}")

Input shape: torch.Size([3, 5])
Output shape: torch.Size([3, 2])
Output:
 tensor([[ 1.6436,  1.0977],
        [ 0.9986,  0.5178],
        [ 0.7449, -0.5846]], grad_fn=<AddmmBackward0>)


In [ ]:
# 10 từ trong từ điển, mỗi từ là một vector 3 chiều
embedding_layer = nn.Embedding(num_embeddings=10, embedding_dim=3)

# Giả sử ta có một câu gồm 4 từ (chỉ số 1, 5, 0, 8)
input_indices = torch.LongTensor([1, 5, 0, 8])

# Lấy vector embedding
embeddings = embedding_layer(input_indices)

print(f"Input shape: {input_indices.shape}") # torch.Size([4])
print(f"Output shape: {embeddings.shape}")      # torch.Size([4, 3])
print(f"Embeddings:\n {embeddings}")

Input shape: torch.Size([4])
Output shape: torch.Size([4, 3])
Embeddings:
 tensor([[ 1.5956, -1.2064, -0.6821],
        [ 1.0334,  0.6921,  0.3002],
        [-2.4618, -0.9638,  1.8745],
        [ 1.6674, -0.1710, -1.1261]], grad_fn=<EmbeddingBackward0>)


In [ ]:
class MyFirstModel(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim):
        super(MyFirstModel, self).__init__()
        # Khai báo các thành phần
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.linear = nn.Linear(embedding_dim, hidden_dim)
        self.activation = nn.ReLU() # Hàm kích hoạt giúp mô hình học được các hàm phi tuyến
        self.output_layer = nn.Linear(hidden_dim, output_dim)

    def forward(self, indices):
        # 1. Chuyển ID từ thành Vector
        embeds = self.embedding(indices)
        # 2. Đi qua lớp ẩn và hàm kích hoạt
        hidden = self.activation(self.linear(embeds))
        # 3. Đi qua lớp đầu ra
        output = self.output_layer(hidden)
        return output

# Khởi tạo mô hình
model = MyFirstModel(vocab_size=100, embedding_dim=16, hidden_dim=8, output_dim=2)

# Kiểm tra với dữ liệu mẫu (1 câu có 4 từ)
input_data = torch.LongTensor([[1, 2, 5, 9]])
output_data = model(input_data)

print(f"Model output shape: {output_data.shape}") # torch.Size([1, 4, 2])
print(f"Kết quả dự báo đầu ra:\n {output_data}")

Model output shape: torch.Size([1, 4, 2])
Kết quả dự báo đầu ra:
 tensor([[[ 0.3976,  0.2910],
         [-0.0060,  0.1874],
         [ 0.0890,  0.3111],
         [ 0.3223,  0.3382]]], grad_fn=<ViewBackward0>)
